version: '3'
services:
#  esb:
#    build: .
#    ports:
#      - "8080:8080"
#      - "8000:8000"
#    links:
#      - mysql
#    depends_on:
#      - mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: swarm
