version: '3'
services:
  esb:
   build: .
   ports:
     - "8080:8080"
   links:
     - mysql
   depends_on:
     - mysql
   volumes:
     - .:/SwarmESB
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: swarm
